In [1]:
import argparse
import os
import pickle
import pandas as pd

%matplotlib inline
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

from numpy.linalg import solve

from scipy.optimize import approx_fprime

np.random.seed(1337)

def error_plot(ys, yscale='log'):
    plt.figure(figsize=(8, 8))
    plt.xlabel('Step')
    plt.ylabel('Error')
    plt.yscale(yscale)
    plt.plot(range(len(ys)), ys)

In [71]:
A = np.eye(3)
b = np.zeros([3,1])
x0 = np.random.normal(0,1,(3,1)).ravel()

In [74]:
x0

array([-1.37073656,  1.4252914 , -0.27946391])

In [75]:
def func(x):
    x = x.reshape(3, 1)
    z = A.dot(x)-b
    return 0.5*z.T.dot(z)[0][0]

def grad(x):
    x = x.reshape(3, 1)
    return A.T.dot(A.dot(x)-b)

In [76]:
from scipy.optimize import approx_fprime, check_grad

func(x0)

1.994237180068953

In [78]:
grad(x0)

array([[-1.37073656],
       [ 1.4252914 ],
       [-0.27946391]])

In [79]:
approx_fprime(x0, func, epsilon=0)

array([-1.37073656,  1.4252914 , -0.27946392])

In [1]:
from randomom import sample

In [20]:
sample(range(1,82),1)

[20]